version: '2'

services:
    taiga-front:
        build: taiga-front
        environment:
          - "VHOST=taiga.gtech.local"
          - "TAIGA_BACK_HOST=taiga-back"
          - "TAIGA_BACK_PORT=8000"
        ports:
         - 80:80
        depends_on:
          - taiga-back
        links:
          - taiga-back
        volumes_from:
          - taiga-back:ro
         
    taiga-back:
        build: taiga-back
        environment:
          - "VHOST=taiga.gtech.local"
          - "TAIGA_DB_HOST=postgres"
          - "TAIGA_DB_NAME=taigadb"
          - "TAIGA_DB_USER=taiga"
          - "TAIGA_DB_PASSWORD=password"
        ports:
         - 8000:8000
        links:
          - postgres
        depends_on:
          - postgres
        volumes:
          - ./media:/taiga-back/media

    postgres:
      image: postgres
      environment:
        POSTGRES_DB: taigadb
        POSTGRES_USER: taiga
        POSTGRES_PASSWORD: password
      volumes:
        - ./pgdata:/var/lib/postgresql/data
